### ISSUE TITLE
Portfolio URL didn't work

### ISSUE THREAD

**Issue by therohanparmar** [tanmay007thor/tanmay007thor#1]
Hello @tanmay007thor,

This URL is not working when I click on it and try to open it.
https://prnt.sc/fJOcFTA2EThA

**Comment by tanmay007thor** [comment]
Thank you for bringing this to my attention. I will update it as soon as possible. In the meantime, you can follow this link: https://tanmay-dev.netlify.app/."

Let me know if you'd like any adjustments!
